
owner: LibreScore # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: LibreScore

sites:
  - name: LibreScore App
    url: $LIBRESCORE_APP_STATUS_ENDPOINT
    icon: https://raw.githubusercontent.com/LibreScore/dl-librescore/master/images/logo.png
  - name: LibreScore Weblate
    url: https://weblate.librescore.org/
#   icon: 

assignees:
  - PeterNjeim

status-website:
  cname: status.librescore.org
  theme: light
  logoUrl: https://avatars.githubusercontent.com/u/63520195
  favicon: https://avatars.githubusercontent.com/u/63520195
  faviconSvg: https://librescore.org/logo.svg
  name: LibreScore Status
  navbar:
    - title: Status
      href: /
    - title: Github Home
      href: https://github.com/LibreScore

i18n:
  footer: 🄯 [LibreScore](https://github.com/LibreScore)

workflowSchedule:
  responseTime: "0 * * * *"
  graphs: "10 */2 * * *"
