
owner: LibreScore # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: LibreScore App
    url: $LIBRESCORE_APP_STATUS_ENDPOINT
    icon: https://raw.githubusercontent.com/LibreScore/dl-librescore/master/images/logo.png
    assignees:
      - PeterNjeim

status-website:
  cname: status.librescore.org
  theme: ocean
  logoUrl: https://avatars.githubusercontent.com/u/63520195
  name: LibreScore Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
